//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IOT.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserRole
    {
        public Nullable<int> UserID { get; set; }
        public Nullable<int> RoleID { get; set; }
        public int UseRoleID { get; set; }
    }
}
